# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go build

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.5'

    - name: Build
      run: |
          mkdir -p dist
          go build -o dist/DE-linux-amd64 ./main.go # 编译 Linux 64 位版本
          GOOS=darwin GOARCH=amd64 go build -o dist/DE-darwin-amd64 ./main.go # 编译 macOS 64 位版本
          GOOS=windows GOARCH=amd64 go build -o dist/DE-windows-amd64.exe ./main.go # 编译 Windows 64 位版本

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的 token
      with:
        tag_name: ${{ github.ref }} # 使用触发工作流的标签
        release_name: Release ${{ github.ref_name }} # Release 名称
        draft: false # 是否创建为草稿
        prerelease: false # 是否为预发布版本
        body: | # Release 描述
          This is an automated release created by GitHub Actions.
          
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }} # 从触发事件中获取上传 URL
        asset_path: dist/DE-linux-amd64
        asset_name: DE-linux-amd64
        asset_content_type: application/octet-stream

    - name: Upload Release Assets (macOS)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/DE-darwin-amd64
        asset_name: DE-darwin-amd64
        asset_content_type: application/octet-stream

    - name: Upload Release Assets (Windows)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/DE-windows-amd64.exe
        asset_name: DE-windows-amd64.exe
        asset_content_type: application/octet-stream
